# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'open_file_test_with_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for open_file_test_with_ios
  install_all_flutter_pods(flutter_application_path)

end
